import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { PostT } from "@/types/types";
import { fetchAllPosts } from "@/api/api";

const inter = Inter({ subsets: ["latin"] });

const Index = () => {
  const [data, setData] = useState<PostT[]>([]);

  useEffect(() => {
    const fetchPosts = async () => {
      const posts = await fetchAllPosts();
      setData(posts);
    };
    fetchPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${inter.className} ${styles.center} text`}>
          Witam na moim blogu
        </div>

        <div className="posts">
          {data?.map((post, index) => (
            <div className="post" key={post.name}>
              <p className="title">Post nr {index}</p>
              <p className="author">
                Autor: {post.email.slice(0, post.email.indexOf("@"))}
              </p>
              <p>{post.body}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Index;
