import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { PostT } from "@/types/types";
import { fetchAllPosts } from "@/api/api";
import Post from "@/components/Post";
import { GetServerSideProps } from "next";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  posts: PostT[];
};

const Index = ({ posts }: Props) => {
  return (
    <>
      <Head>
        <title>Mój ekstra blog</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${inter.className} ${styles.center} text`}>
          Witam na moim blogu
        </div>

        <div className="posts">
          {posts?.map((post) => (
            <Post key={post.id} post={post} />
          ))}
        </div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const posts = await fetchAllPosts();
  return {
    props: { posts },
  };
};

export default Index;
